import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { exportWorkspaceJson } from "../../domain/export/workspace-export";
import { downloadText } from "../../infrastructure/export/download";
import type { WorkspaceRecord } from "../../infrastructure/storage/ideascope-database";
import { WorkspaceRepository } from "../../infrastructure/storage/workspace-repository";
import { Button, Dialog } from "../../shared/ui";
import styles from "./ProjectLibrary.module.css";
export function ProjectLibrary() {
  const navigate=useNavigate();const [items,setItems]=useState<WorkspaceRecord[]>([]);const [deleting,setDeleting]=useState<WorkspaceRecord|null>(null);const [confirmation,setConfirmation]=useState("");const repository=useMemo(()=>new WorkspaceRepository(),[]);
  const refresh=useCallback(async()=>{try{setItems(await repository.list());}catch{setItems([]);}},[repository]);useEffect(()=>{if(!("indexedDB" in globalThis))return;let active=true;void repository.list().then(value=>{if(active)setItems(value);},()=>{if(active)setItems([]);});return()=>{active=false;};},[repository]);
  async function exportItem(item:WorkspaceRecord){const value=await repository.get(item.id);if(value)downloadText(`${item.title}.json`,"application/json",exportWorkspaceJson(value,"0.6.3"));}
  const visible=items.filter(({archivedAt})=>!archivedAt);
  return <section className={styles.library} aria-labelledby="history-title"><div><small>EXPLORATION HISTORY</small><h2 id="history-title">探索历史</h2><p>保存在当前浏览器，不会自动同步。</p></div>{visible.length?<div className={styles.list}>{visible.map(item=><article key={item.id} tabIndex={0} onClick={()=>void navigate(`/workspace/${item.id}`)} onKeyDown={event=>{if(event.key==="Enter")void navigate(`/workspace/${item.id}`);}}><div className={styles.main}><strong>{item.title}</strong><span>{item.seedIdea}</span></div><div className={styles.meta}><span>{new Date(item.updatedAt).toLocaleString()}</span><span>{item.paperIds.length} 篇文献 · {item.branchIds.length} 条分支</span></div><details onClick={event=>event.stopPropagation()}><summary aria-label={`${item.title} 的更多操作`}>···</summary><div className={styles.menu}><button onClick={()=>{const title=window.prompt("新项目名称",item.title);if(title)void repository.rename(item.id,title).then(refresh);}}>重命名</button><button onClick={()=>void exportItem(item)}>导出</button><button onClick={()=>{setDeleting(item);setConfirmation("");}}>删除</button></div></details></article>)}</div>:<p className={styles.empty}>还没有探索记录。写下一个研究想法即可开始。</p>}<Dialog open={Boolean(deleting)} title="删除探索项目" onClose={()=>setDeleting(null)}><p>此操作不可撤销。请输入项目名称“{deleting?.title}”确认。</p><input aria-label="输入项目名称确认删除" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/><div className={styles.actions}><Button onClick={()=>setDeleting(null)}>取消</Button><Button disabled={confirmation!==deleting?.title} onClick={()=>{if(deleting)void repository.delete(deleting.id,confirmation).then(()=>{setDeleting(null);void refresh();});}}>确认删除</Button></div></Dialog></section>;
}
