import { MoreHorizontal, Plus } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { exportWorkspaceJson } from "../../domain/export/workspace-export";
import { createEmptyWorkspace } from "../../domain/workspace/create-workspace";
import { downloadText } from "../../infrastructure/export/download";
import type { WorkspaceRecord } from "../../infrastructure/storage/ideascope-database";
import { WorkspaceRepository } from "../../infrastructure/storage/workspace-repository";
import { Button, Dialog } from "../../shared/ui";
import styles from "./SessionSidebar.module.css";
export function SessionSidebar({activeId,refreshKey=0}:{activeId?:string;refreshKey?:number}){const navigate=useNavigate();const[items,setItems]=useState<WorkspaceRecord[]>([]);const[deleting,setDeleting]=useState<WorkspaceRecord|null>(null);const[confirmation,setConfirmation]=useState("");const repository=useMemo(()=>new WorkspaceRepository(),[]);const refresh=useCallback(()=>void repository.list().then(value=>setItems(value.filter(item=>!item.archivedAt))),[repository]);useEffect(()=>{let active=true;void repository.list().then(value=>{if(active)setItems(value.filter(item=>!item.archivedAt));});return()=>{active=false;};},[refreshKey,repository]);async function create(){const value=createEmptyWorkspace();const result=await repository.save(value);if(result.status==="saved")void navigate(`/workspace/${value.workspace.id}`);}async function exportItem(item:WorkspaceRecord){const value=await repository.get(item.id);if(value)downloadText(`${item.title}.json`,"application/json",exportWorkspaceJson(value,"0.6.4"));}return <aside className={styles.sidebar}><div className={styles.brand}>IdeaScope</div><button className={styles.newButton} onClick={()=>void create()}><Plus size={16}/>新建探索</button><p className={styles.label}>探索会话</p><nav>{items.map(item=><div key={item.id} className={`${styles.item} ${item.id===activeId?styles.active:""}`}><button className={styles.open} onClick={()=>void navigate(`/workspace/${item.id}`)}><strong>{item.title}</strong><span>{new Date(item.updatedAt).toLocaleDateString()}</span></button><details className={styles.actions}><summary aria-label={`${item.title} 的更多操作`}><MoreHorizontal size={15}/></summary><div><button onClick={()=>{const title=window.prompt("新的会话名称",item.title);if(title)void repository.rename(item.id,title).then(refresh);}}>重命名</button><button onClick={()=>void exportItem(item)}>导出</button><button onClick={()=>{setDeleting(item);setConfirmation("");}}>删除</button></div></details></div>)}</nav>{!items.length&&<p className={styles.empty}>还没有探索会话</p>}<Dialog open={Boolean(deleting)} title="删除探索会话" onClose={()=>setDeleting(null)}><p>删除后无法恢复。请输入“{deleting?.title}”确认。</p><input aria-label="输入会话名称确认删除" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/><div className={styles.confirm}><Button onClick={()=>setDeleting(null)}>取消</Button><Button disabled={confirmation!==deleting?.title} onClick={()=>{if(deleting)void repository.delete(deleting.id,confirmation).then(()=>{if(deleting.id===activeId)void navigate("/");setDeleting(null);refresh();});}}>确认删除</Button></div></Dialog></aside>;}
